name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build the docker image
        run: |
          docker build . -f Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/test:latest

      - name: push the docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/test:latest
